### ISSUE TITLE
add the functionality to inputbox to add the new area when ruturn is checked

### ISSUE THREAD

**Issue by cademis** [cademis/todo-js#14]
https://github.com/cademis/todo-js/blob/79dbfb70285aa9572056d565e253dcd074ce04b0/src/logic.js#L41

**Comment by LOGESH-B** [comment]
hii @cademis 
i am interested to do this
![image](https://github.com/cademis/todo-js/assets/86541143/094aefe9-0706-4e33-8be3-b99e6357c36a)
you are asking like this

**Comment by cademis** [comment]
> hii @cademis 
> 
> i am interested to do this
> 
> ![image](https://github.com/cademis/todo-js/assets/86541143/094aefe9-0706-4e33-8be3-b99e6357c36a)
> 
> you are asking like this

Are you needing help?
